export default {
  alterEgo: {
    title: `Alter Ego on Toast`,
    blurb: `A sub-ultimate appetizer`,
    description: `Have a go and chat with yourself. Odd at first, it can help casting-off your mind's singularity.`,
  },
  obama: {
    title: `Obama's Chili`,
    blurb: `A good meal when seeking expert advice or inspiration`,
    description: `Pick someone you hold in high-regard.`,
    left: `You`,
    right: `That someone`,
  },
  dosdonts: {
    title: `Dos and Don'ts Egg Bites`,
    blurb: `Get charged for the day`,
    left: `Things you should do`,
    right: `Those you shouldn't`,
    comment: `optional: a chopstick you must break if you don't stick to it`,
  },
  chatdelune: {
    title: `Chat De Lune`,
    blurb: `A dish in honour of the queen of reflective practice - Jennifer Moon`,
    description: `Pick a recent experience – a meeting, a day, or a month long project – and reflect on the feelings and behaviour of yourself and those involved. What could you have done better? What are the main takeaways`,
  },
  devil: {
    title: `Devilfish & Avocado Maki`,
    blurb: `About to do expend some time or money?`,
    description: `How can this go wrong? How could you be wrong?`,
    left: `You`,
    right: `Devil's advocate`,
  },
  forAgainst: {
    title: `Sweet & Sour Tofu`,
    blurb: `A dish with contrasting views`,
    left: `For`,
    right: `Against`,
    comment: `(also pros & cons)`,
  },
  mindTheGap: {
    title: `Mind The Gap Flamiche`,
    blurb: `A dish that hardly ever goes to plan`,
    left: `Plan`,
    right: `Actuality`,
  },
  betterSelf: {
    title: `Bettered Fish & Chips`,
    blurb: `Never perfectly cooked, but always better`,
    left: `Yourself`,
    right: `The self you want to be`,
  },
  empathy: {
    title: `Empathy Torpedo`,
    blurb: `A good munch for the upset`,
    left: `What you feel`,
    right: `What the other may feel and why`,
  },
  wolf: {
    title: `Winston Wolfe's Pasta`,
    blurb: `Hand made dish for the reactive`,
    left: `Problem`,
    right: `Solutions`,
    comment: `(singular vs plural)`,
  },
};
